import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Building2, Crown, Edit3, EyeOff, Plus, LogOut } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { EmptyState, PageLoading } from '../components/Ui'
import { api } from '../lib/api'
import { price } from '../lib/catalog'
import { useGeoDomStore } from '../store/useGeoDomStore'
import { DemandSharePanel } from '../components/DemandSharePanel'
import type { Apartment } from '../types'
const status: Record<string,string> = { published:'Опубликовано', draft:'Черновик', hidden:'Скрыто', deleted:'Удалено' }
export function Account() {
  const user = useGeoDomStore(state => state.user); const setUser = useGeoDomStore(state => state.setUser); const savedIds = useGeoDomStore(state => state.savedIds); const navigate = useNavigate(); const [items,setItems] = useState<Apartment[]>([]); const [catalog,setCatalog] = useState<Apartment[]>([]); const [loading,setLoading] = useState(true); const [error,setError] = useState(''); const [busy,setBusy] = useState('')
  const savedItems = useMemo(() => catalog.filter(item => savedIds.includes(item.id)),[catalog,savedIds])
  useEffect(() => { Promise.all([api.mine(),api.list()]).then(([mine,all]) => { setItems(mine); setCatalog(all) }).catch(e => setError(e.message)).finally(() => setLoading(false)) },[])
  async function hide(item: Apartment) { if (!window.confirm('Скрыть объявление из каталога?')) return; setBusy(item.id); try { await api.hide(item.id); setItems(prev => prev.map(x => x.id === item.id ? {...x,status:'hidden'} : x)) } catch(e) { setError(e instanceof Error ? e.message : 'Не удалось скрыть объявление') } finally { setBusy('') } }
  function logout() { api.logout(); setUser(null); navigate('/') }
  return <div className="shell account-page"><div className="account-hero"><div><span className="eyebrow light"><span className="eyebrow-line"/> ЛИЧНЫЙ КАБИНЕТ</span><h1>Здравствуйте, <em>{user?.login}.</em></h1><p>Здесь можно управлять объявлениями и вернуться к сохранённым квартирам.</p></div><div className="account-avatar">{user?.login[0].toUpperCase()}</div></div><DemandSharePanel/><Link to="/pro" className="account-pro-card"><span><Crown size={20}/></span><div><small>GEODOM PRO · ДЕМО</small><b>CRM, квалифицированные лиды, продвижение и аналитика</b><p>Для риелторов, агентств и застройщиков.</p></div><ArrowRight size={20}/></Link><div className="account-heading"><div><span className="eyebrow"><span className="eyebrow-line"/> МОЯ НЕДВИЖИМОСТЬ</span><h2>Мои объявления <small>{items.length}</small></h2></div><Link className="button dark" to="/new"><Plus size={18}/> Добавить квартиру</Link></div>{error && <div className="form-error" role="alert">{error}</div>}{loading ? <PageLoading/> : items.length ? <div className="account-list">{items.map(item => <div className="account-item" key={item.id}><div className="account-item-image">{item.photos[0] ? <img src={item.photos[0].url} alt=""/> : <Building2 size={32}/>}</div><div className="account-item-copy"><span className={`status status-${item.status}`}>{status[item.status]}</span><h3>{item.title}</h3><p>{item.address}</p><b>{price(item.price)}</b></div><div className="account-item-actions"><Link to={`/apartments/${item.id}`} className="small-action">Открыть <ArrowRight size={16}/></Link><Link to={`/apartments/${item.id}/edit`} className="small-action"><Edit3 size={16}/> Изменить</Link>{item.status !== 'hidden' && <button className="small-action danger" disabled={busy === item.id} onClick={() => hide(item)}><EyeOff size={16}/> Скрыть</button>}</div></div>)}</div> : <EmptyState title="Пока нет объявлений" message="Добавьте первую квартиру, и она появится здесь." action={<Link className="button dark" to="/new"><Plus size={18}/> Разместить квартиру</Link>}/>}<div className="account-heading saved-heading"><div><span className="eyebrow"><span className="eyebrow-line"/> ВАШ ВЫБОР</span><h2>Сохранённые квартиры <small>{savedItems.length}</small></h2><p>Сохраняются в этом браузере.</p></div></div>{savedItems.length ? <div className="saved-grid">{savedItems.map(item => <Link key={item.id} to={`/apartments/${item.id}`} className="saved-item">{item.photos[0] ? <img src={item.photos[0].url} alt=""/> : <Building2 size={25}/>}<span><b>{item.title}</b><small>{price(item.price)} · {item.district.name}</small></span><ArrowRight size={18}/></Link>)}</div> : <div className="saved-empty">Сохраняйте варианты из персонального подбора, чтобы вернуться к ним позже. <Link to="/#recommendations">Перейти к подбору →</Link></div>}<button className="logout" onClick={logout}><LogOut size={17}/> Выйти из аккаунта</button></div>
}
