import { useState } from 'react'
import { ArrowLeft, ArrowRight, Eye, EyeOff, LockKeyhole, UserRound } from 'lucide-react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { api, isDemo } from '../lib/api'
import { useAuth } from '../App'
export function Auth({ mode }: { mode:'login'|'register' }) {
  const [login,setLogin] = useState(''); const [password,setPassword] = useState(''); const [show,setShow] = useState(false); const [error,setError] = useState(''); const [busy,setBusy] = useState(false)
  const { setUser } = useAuth(); const navigate = useNavigate(); const [params] = useSearchParams(); const next = params.get('next')?.startsWith('/') && !params.get('next')?.startsWith('//') ? params.get('next')! : '/account'
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(''); if (login.trim().length < 3) { setError('Логин должен содержать минимум 3 символа'); return } if (password.length < 6) { setError('Пароль должен содержать минимум 6 символов'); return } setBusy(true); try { if (mode === 'register') await api.register(login.trim(),password); const user = await api.login(login.trim(),password); setUser(user); navigate(next) } catch(e) { setError(e instanceof Error ? e.message : 'Что-то пошло не так') } finally { setBusy(false) } }
  return <div className="auth-page"><div className="auth-image"><Link to="/" className="auth-back"><ArrowLeft size={17}/> На главную</Link><div className="auth-image-content"><span>СРЕДА / КРАСНОЯРСК</span><h2>Найдите место,<br/>в которое хочется<br/><em>возвращаться.</em></h2><p>Не только квартира. Вся жизнь вокруг неё.</p></div></div><div className="auth-form-side"><div className="auth-form-wrap"><span className="eyebrow"><span className="eyebrow-line"/> ЛИЧНЫЙ КАБИНЕТ</span><h1>{mode === 'register' ? 'Создать аккаунт' : 'С возвращением.'}</h1><p>{mode === 'register' ? 'Создайте аккаунт, чтобы разместить свою квартиру.' : 'Войдите, чтобы управлять объявлениями.'}</p><form onSubmit={submit}><label htmlFor="login">Логин</label><div className="input-with-icon"><UserRound size={19}/><input id="login" autoComplete="username" value={login} onChange={e => setLogin(e.target.value)} placeholder="Ваш логин" required/></div><label htmlFor="password">Пароль</label><div className="input-with-icon"><LockKeyhole size={19}/><input id="password" type={show ? 'text' : 'password'} autoComplete={mode === 'register' ? 'new-password' : 'current-password'} value={password} onChange={e => setPassword(e.target.value)} placeholder="Не менее 6 символов" required/><button type="button" onClick={() => setShow(!show)} aria-label={show ? 'Скрыть пароль' : 'Показать пароль'}>{show ? <EyeOff size={19}/> : <Eye size={19}/>}</button></div>{error && <div className="form-error" role="alert">{error}</div>}<button className="button dark auth-submit" disabled={busy}>{busy ? 'Подождите…' : mode === 'register' ? 'Зарегистрироваться' : 'Войти'}<ArrowRight size={18}/></button></form><div className="auth-switch">{mode === 'register' ? 'Уже есть аккаунт?' : 'Ещё нет аккаунта?'} <Link to={`${mode === 'register' ? '/login' : '/register'}?next=${encodeURIComponent(next)}`}>{mode === 'register' ? 'Войти' : 'Зарегистрироваться'}</Link></div>{isDemo && <p className="auth-demo-note">Демо: аккаунт хранится только в вашем браузере. Не используйте настоящий пароль.</p>}</div></div></div>
}
