import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, ArrowUpRight, Building2, Check, ChevronDown, CircleHelp, MapPin, RotateCcw, Search, SlidersHorizontal, Sparkles, X } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { ApartmentCard, EmptyState, PageLoading } from '../components/Ui'
import { MapPanel } from '../components/MapPanel'
import { api, isDemo } from '../lib/api'
import { filterApartments } from '../lib/catalog'
import type { Apartment, CatalogFilters, CatalogSort } from '../types'
const initial: CatalogFilters = { district:'', maxPrice:0, rooms:0, query:'', sort:'recommended' }
export function Catalog() {
  const [items,setItems] = useState<Apartment[]>([]); const [loading,setLoading] = useState(true); const [error,setError] = useState(''); const [params,setParams] = useSearchParams(); const [filtersOpen,setFiltersOpen] = useState(false)
  const [filters,setFilters] = useState<CatalogFilters>(() => ({ ...initial,district:params.get('district') || '',query:params.get('q') || '' }))
  useEffect(() => { api.list().then(setItems).catch(e => setError(e.message)).finally(() => setLoading(false)) },[])
  const districts = useMemo(() => [...new Set(items.map(x => x.district.name))].filter(x => x !== 'Уточняется').sort(),[items])
  const visible = useMemo(() => filterApartments(items,filters),[items,filters])
  const districtCards = useMemo(() => districts.map(name => { const group = items.filter(x => x.district.name === name); return { name, count:group.length, score:Math.round(group.reduce((sum,x) => sum+(x.recommendation.score || 0),0)/group.length), photo:group[0]?.photos[0]?.url, description:group[0]?.district.description } }).sort((a,b) => b.score-a.score).slice(0,3),[items,districts])
  function change<K extends keyof CatalogFilters>(key: K,value: CatalogFilters[K]) { setFilters(prev => ({ ...prev,[key]:value })) }
  function reset() { setFilters(initial); setParams({}) }
  function submit(e: React.FormEvent) { e.preventDefault(); setParams(filters.query ? { q:filters.query } : {}) }
  function pickDistrict(name:string) { change('district',filters.district === name ? '' : name); document.getElementById('catalog')?.scrollIntoView({behavior:'smooth',block:'start'}) }
  const activeCount = Number(!!filters.district)+Number(!!filters.maxPrice)+Number(!!filters.rooms)
  return <div className="dashboard-page"><div className="shell dashboard-grid"><aside className={`dashboard-sidebar ${filtersOpen ? 'open' : ''}`}><div className="sidebar-heading"><h2>Ваши параметры</h2><button onClick={reset}>Сбросить</button><button className="mobile-only-close" onClick={() => setFiltersOpen(false)} aria-label="Закрыть фильтры"><X size={19}/></button></div><div className="sidebar-block"><span className="sidebar-label">Бюджет на жильё</span><div className="segmented"><span className="active">Покупка</span><span>Красноярск</span></div><label className="sidebar-label inline" htmlFor="budget">Максимальная стоимость</label><select id="budget" value={filters.maxPrice} onChange={e => change('maxPrice',Number(e.target.value))}><option value="0">Любая цена</option><option value="5000000">До 5 000 000 ₽</option><option value="7000000">До 7 000 000 ₽</option><option value="9000000">До 9 000 000 ₽</option><option value="12000000">До 12 000 000 ₽</option></select></div><div className="sidebar-block"><label className="sidebar-label" htmlFor="district">Район города</label><select id="district" value={filters.district} onChange={e => change('district',e.target.value)}><option value="">Все районы</option>{districts.map(d => <option key={d}>{d}</option>)}</select></div><div className="sidebar-block"><span className="sidebar-label">Количество комнат</span><div className="room-options">{[[0,'Все'],[1,'1'],[2,'2'],[3,'3']].map(([n,label]) => <button key={n} className={filters.rooms === n ? 'selected' : ''} onClick={() => change('rooms',Number(n))}>{label}</button>)}</div></div><div className="sidebar-block priority-block"><span className="sidebar-label">Что важно в районе</span><p>Сравнивайте реальные признаки из карточек квартир</p><div className="priority-list"><span><Check size={15}/> Школы поблизости</span><span><Check size={15}/> Парки и зелёные зоны</span><span><Check size={15}/> Доступный транспорт</span><span><Check size={15}/> Планы развития</span></div></div><button className="sidebar-apply" onClick={() => { setFiltersOpen(false); document.getElementById('catalog')?.scrollIntoView({behavior:'smooth'}) }}>Показать {visible.length} квартир <ArrowRight size={18}/></button><button className="sidebar-reset" onClick={reset}><RotateCcw size={15}/> Сбросить параметры</button></aside>
  <div className="dashboard-main"><div className="dashboard-intro"><div><span className="dashboard-kicker">АНАЛИЗ ГОРОДСКОЙ СРЕДЫ · КРАСНОЯРСК</span><h1>Выберите квартиру <em>с пониманием района</em></h1><p>Сравнивайте предложения, смотрите инфраструктуру рядом и узнавайте, что планируется построить. Все важные данные — в одном месте.</p></div><div className="intro-badge"><span className="intro-badge-icon"><Building2 size={22}/></span><div><b>{districts.length || '—'} районов</b><small>для осознанного выбора</small></div><ArrowUpRight size={16}/></div></div><form className="dashboard-search" onSubmit={submit}><Search size={19}/><input aria-label="Поиск по району или адресу" value={filters.query} onChange={e => change('query',e.target.value)} placeholder="Поиск по району, улице или адресу…"/><button type="submit">Найти <ArrowRight size={16}/></button></form><div className="map-panel"><div className="map-topbar"><div><span className="map-tab active"><MapPin size={16}/> Карта квартир</span><span className="map-tab secondary">Красноярск и районы</span></div><div className="map-topbar-note"><span className="pulse-dot"/> {visible.length} предложений на карте</div></div>{loading ? <PageLoading/> : error ? <EmptyState title="Карта недоступна" message={error}/> : <MapPanel items={visible} selectedDistrict={filters.district} onDistrict={pickDistrict}/>}<div className="map-caption"><CircleHelp size={15}/> Нажмите на цену квартиры или оценку района, чтобы изучить подробнее. <span>Картография © OpenStreetMap</span></div></div>
  <div className="dashboard-section-title"><div><h2>Районы <span>Красноярска</span></h2><p>Посмотрите, как устроена среда рядом с жильём</p></div><span className="mini-label">{isDemo ? 'ДЕМОНСТРАЦИОННЫЕ ОЦЕНКИ' : 'ДАННЫЕ СЕРВЕРА'}</span></div><div className="district-cards">{districtCards.map((d,i) => <button className={`district-card ${filters.district === d.name ? 'chosen' : ''}`} key={d.name} onClick={() => pickDistrict(d.name)}><div className="district-image">{d.photo && <img src={d.photo} alt=""/>}<span>{i === 0 ? '✦ Рекомендуем' : `${d.count} предложений`}</span></div><div className="district-card-head"><h3>{d.name}</h3><b><Sparkles size={16}/>{(d.score/10).toFixed(1)} <small>/ 10</small></b></div><p>{d.description}</p><div className="district-card-bottom">Смотреть квартиры <ArrowRight size={16}/></div></button>)}</div>
  <section className="listings-section" id="catalog"><div className="dashboard-section-title listings-title"><div><h2>Подходящие <span>квартиры</span></h2><p>{loading ? 'Загружаем предложения…' : `${visible.length} предложений по вашим параметрам`}</p></div><div className="listings-actions"><button className="mobile-filter-button" onClick={() => setFiltersOpen(true)}><SlidersHorizontal size={17}/> Фильтры {activeCount > 0 && <b>{activeCount}</b>}</button><label htmlFor="sort">Сортировка</label><div className="select-wrap"><select id="sort" value={filters.sort} onChange={e => change('sort',e.target.value as CatalogSort)}><option value="recommended">По оценке</option><option value="price_asc">Цена ↑</option><option value="price_desc">Цена ↓</option><option value="area_desc">Площадь ↓</option></select><ChevronDown size={15}/></div></div></div>{loading ? <PageLoading/> : error ? <EmptyState title="Не удалось загрузить квартиры" message={error} action={<button className="button dark" onClick={() => window.location.reload()}>Повторить</button>}/> : visible.length ? <div className="card-grid">{visible.map((item,index) => <ApartmentCard item={item} index={index} key={item.id}/>)}</div> : <EmptyState title="Ничего не нашлось" message="Попробуйте расширить бюджет или выбрать другой район." action={<button className="button dark" onClick={reset}>Сбросить фильтры</button>}/>}</section><div className="dashboard-end"><span><Sparkles size={18}/> Среда помогает смотреть дальше квартиры</span><Link to="/register">Разместить своё объявление <ArrowRight size={17}/></Link></div></div></div></div>
}
