import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowUpRight, Bookmark, BusFront, Check, GitCompareArrows, GraduationCap, MapPin, School, Share2, TreePine } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { EmptyState, PageLoading } from '../components/Ui'
import { ScorePanel } from '../components/ScorePanel'
import { PhotoGallery } from '../components/PhotoGallery'
import { MortgageCalculator } from '../components/MortgageCalculator'
import { RentVsBuyCalculator } from '../components/RentVsBuyCalculator'
import { api, isDemo } from '../lib/api'
import { area, distance, price } from '../lib/catalog'
import type { Apartment } from '../types'
import { useGeoDomStore } from '../store/useGeoDomStore'
import { resolvePhotoUrl } from '../lib/media'
import { loadLastRecommendation } from '../lib/recommendations'
const statusLabel: Record<string,string> = { planned:'Планируется', approved:'Утверждено', construction:'Строится', completed:'Завершено', cancelled:'Отменено' }
export function Detail() {
  const { id = '' } = useParams(); const savedIds = useGeoDomStore(state => state.savedIds); const comparedIds = useGeoDomStore(state => state.comparedIds); const defaultDownPayment = useGeoDomStore(state => state.preferences.down_payment); const toggleSaved = useGeoDomStore(state => state.toggleSaved); const toggleCompared = useGeoDomStore(state => state.toggleCompared); const [item,setItem] = useState<Apartment|null>(null); const [error,setError] = useState(''); const [loading,setLoading] = useState(true); const [copied,setCopied] = useState(false)
  useEffect(() => { setLoading(true); api.detail(id).then(setItem).catch(e => setError(e.message)).finally(() => setLoading(false)) },[id])
  if (loading) return <div className="shell detail-loading"><PageLoading/></div>
  if (error || !item) return <div className="shell detail-loading"><EmptyState title="Квартира не найдена" message={error || 'Возможно, объявление скрыто.'} action={<Link className="button dark" to="/">К каталогу</Link>}/></div>
  const apartment=item
  const images = apartment.photos.map(resolvePhotoUrl).filter((url):url is string => !!url); const f = apartment.features; const validCoordinates = apartment.latitude !== 0 && apartment.longitude !== 0; const saved = savedIds.includes(apartment.id); const compared = comparedIds.includes(apartment.id)
  function track(event:'save'|'compare') {
    const response=loadLastRecommendation()
    if (!response) return
    const position=response.items.findIndex(candidate => String(candidate.apartment_id) === apartment.id)
    if (position < 0) return
    void api.event({ request_id:response.request_id,event,entity_type:'apartment',entity_id:apartment.id,position:position+1 }).catch(() => {})
  }
  function saveCurrent() {
    const active=toggleSaved(apartment.id)
    if (active) track('save')
  }
  function compareCurrent() {
    const wasCompared=comparedIds.includes(apartment.id)
    const active=toggleCompared(apartment.id)
    if (!wasCompared && active) track('compare')
  }
  async function share() { try { await navigator.clipboard.writeText(window.location.href); setCopied(true); setTimeout(() => setCopied(false), 2000) } catch { setCopied(false) } }
  return <div className="detail-page shell"><div className="detail-top"><Link to="/" className="back-link"><ArrowLeft size={17}/> Все квартиры</Link><div className="detail-top-right"><span>ОБЪЕКТ / {item.id.slice(0,8).toUpperCase()}</span><button className={`share-button ${saved ? 'active' : ''}`} onClick={saveCurrent}><Bookmark size={17} fill={saved ? 'currentColor' : 'none'}/> {saved ? 'Сохранено' : 'Сохранить'}</button><button className={`share-button ${compared ? 'active' : ''}`} onClick={compareCurrent} disabled={!compared && comparedIds.length >= 3}><GitCompareArrows size={17}/> {compared ? 'В сравнении' : 'Сравнить'}</button><button className="share-button" onClick={share}>{copied ? <Check size={17}/> : <Share2 size={17}/>} {copied ? 'Ссылка скопирована' : 'Поделиться'}</button></div></div><div className="detail-heading"><div><span className="eyebrow"><span className="eyebrow-line"/> {item.district.name.toUpperCase()} РАЙОН</span><h1>{item.title}</h1><p><MapPin size={17}/>{item.address}</p></div><div className="detail-heading-price"><span>СТОИМОСТЬ</span><b>{price(item.price)}</b><small>{price(Math.round(item.price / item.area))} / м²</small></div></div>
  <PhotoGallery images={images} title={item.title}/>
  <div className="detail-layout"><div className="detail-content"><section className="detail-section"><div className="section-kicker">01 / О КВАРТИРЕ</div><h2>Пространство для жизни</h2><div className="spec-grid"><div><b>{item.rooms === 0 ? 'Студия' : item.rooms}</b><span>{item.rooms === 0 ? 'формат' : 'комнаты'}</span></div><div><b>{area(item.area)}</b><span>общая площадь</span></div><div><b>{item.floor} / {item.total_floors}</b><span>этаж</span></div>{item.kitchen_area && <div><b>{area(item.kitchen_area)}</b><span>кухня</span></div>}</div><p className="description">{item.description || 'Описание не добавлено.'}</p><div className="secondary-specs">{item.building_year && <span>Год постройки <b>{item.building_year}</b></span>}{item.building_type && <span>Тип дома <b>{item.building_type}</b></span>}{item.renovation && <span>Состояние <b>{item.renovation}</b></span>}</div></section>
  <section className="detail-section"><div className="section-kicker">02 / РАЙОН</div><h2>Всё, что вокруг</h2><p className="section-intro">{item.district.description || 'Описание района появится после обработки адреса.'}</p>{item.district.id !== 'pending' ? <><div className="infra-grid"><div><GraduationCap/><b>{f.schools_1km}</b><span>школы в радиусе 1 км</span></div><div><TreePine/><b>{f.parks_1km}</b><span>парка в радиусе 1 км</span></div><div><School/><b>{f.kindergartens_1km}</b><span>детских сада рядом</span></div><div><BusFront/><b>{f.nearest_transport_m} м</b><span>до транспорта</span></div></div><div className="distance-list"><div><span>Ближайшая школа</span><b>{distance(f.nearest_school_m)}</b></div><div><span>Ближайший парк</span><b>{distance(f.nearest_park_m)}</b></div><div><span>Общественный транспорт</span><b>{distance(f.nearest_transport_m)}</b></div></div></> : <div className="info-note">После подключения сервера район и инфраструктура будут рассчитаны по введённому адресу.</div>}{validCoordinates && <a className="map-link" href={`https://yandex.ru/maps/?ll=${item.longitude}%2C${item.latitude}&z=15&pt=${item.longitude}%2C${item.latitude},pm2rdm`} target="_blank" rel="noopener noreferrer"><MapPin size={18}/> Посмотреть место на карте <ArrowUpRight size={18}/></a>}</section>
  <section className="detail-section"><div className="section-kicker">03 / ПЕРСПЕКТИВА</div><h2>Что планируется рядом</h2><p className="section-intro">Будущие объекты показаны отдельно от оценки квартиры. Планы и сроки могут меняться — проверяйте первоисточник.</p>{item.development_projects.length ? <div className="projects-list">{item.development_projects.map(p => <div className="project" key={p.id}><div className="project-icon"><BuildingMark type={p.type}/></div><div className="project-copy"><div className="project-meta">{p.type} · {distance(p.distance_m)} · {statusLabel[p.status] || p.status}</div><h3>{p.name}</h3><p>{p.description}</p><small>{p.planned_completion_year ? `Плановый срок: ${p.planned_completion_year} · ` : ''}Источник: {p.source_url ? <a href={p.source_url} target="_blank" rel="noopener noreferrer">{p.source_name} ↗</a> : p.source_name}</small></div></div>)}</div> : <div className="info-note">В доступных данных нет подтверждённых будущих объектов рядом с этой квартирой.</div>}</section><section className="detail-section finance-section"><div className="section-kicker">04 / ФИНАНСЫ</div><h2>Как выглядит покупка в цифрах</h2><p className="section-intro">Сначала сравните ипотечные сценарии по публичным условиям банков, затем проверьте сценарий «купить или снимать». Все допущения редактируемые.</p><div className="finance-tools"><MortgageCalculator apartmentPrice={item.price} defaultDownPayment={defaultDownPayment}/><RentVsBuyCalculator apartmentPrice={item.price} defaultDownPayment={defaultDownPayment}/></div></section>{(item.source_url || item.upstream_source) && <section className="detail-section source-section"><div className="section-kicker">05 / ИСТОЧНИК</div><h2>Происхождение объявления</h2><p className="section-intro">Источник показывается отдельно от оценки GeoDom.</p><div className="source-card"><div><span>Источник</span><b>{item.upstream_source?.toLowerCase() === 'sibdom' ? 'СИБДОМ' : item.upstream_source || 'Источник объявления'}</b></div>{item.source_updated_at && <div><span>Обновлено</span><b>{new Date(item.source_updated_at).toLocaleDateString('ru-RU')}</b></div>}{item.source_url && <a href={item.source_url} target="_blank" rel="noopener noreferrer">Открыть оригинал <ArrowUpRight size={15}/></a>}</div></section>}</div>
  <aside className="detail-aside"><ScorePanel apartment={item}/><div className="aside-note"><span>ВАШ СЛЕДУЮЩИЙ ШАГ</span><h3>Нашли подходящий вариант?</h3><p>Сохраните квартиру или ссылку и сравните её с другими предложениями.</p><button className={`button light ${saved ? 'active' : ''}`} onClick={() => toggleSaved(apartment.id)}><Bookmark size={17} fill={saved ? 'currentColor' : 'none'}/> {saved ? 'Сохранено' : 'Сохранить квартиру'}</button><Link className="button light" to="/compare" onClick={() => { if (!compared && comparedIds.length < 3) compareCurrent() }}><GitCompareArrows size={17}/> {compared ? 'Открыть сравнение' : 'Добавить и сравнить'}</Link><button className="button light" onClick={share}>{copied ? 'Скопировано ✓' : 'Скопировать ссылку'} <ArrowUpRight size={17}/></button></div></aside></div>{isDemo && <div className="demo-disclaimer">Фотографии, цены, адреса, оценки и проекты на этой странице — демонстрационные данные. Это не реальные объявления.</div>}</div>
}
function BuildingMark({type}: {type:string}) { return type === 'Парк' ? <TreePine size={22}/> : type === 'Школа' ? <GraduationCap size={22}/> : <BusFront size={22}/> }
