import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowUpRight, BusFront, Check, ChevronLeft, ChevronRight, GraduationCap, MapPin, School, Share2, Sparkles, TreePine } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { EmptyState, PageLoading } from '../components/Ui'
import { api, isDemo } from '../lib/api'
import { area, distance, price } from '../lib/catalog'
import type { Apartment } from '../types'
const statusLabel: Record<string,string> = { planned:'Планируется', approved:'Утверждено', construction:'Строится', completed:'Завершено', cancelled:'Отменено' }
export function Detail() {
  const { id = '' } = useParams(); const [item,setItem] = useState<Apartment|null>(null); const [error,setError] = useState(''); const [loading,setLoading] = useState(true); const [photo,setPhoto] = useState(0); const [copied,setCopied] = useState(false)
  useEffect(() => { setLoading(true); api.detail(id).then(setItem).catch(e => setError(e.message)).finally(() => setLoading(false)) },[id])
  if (loading) return <div className="shell detail-loading"><PageLoading/></div>
  if (error || !item) return <div className="shell detail-loading"><EmptyState title="Квартира не найдена" message={error || 'Возможно, объявление скрыто.'} action={<Link className="button dark" to="/">К каталогу</Link>}/></div>
  const images = item.photos.map(x => x.url); const f = item.features; const validCoordinates = item.latitude !== 0 && item.longitude !== 0
  async function share() { try { await navigator.clipboard.writeText(window.location.href); setCopied(true); setTimeout(() => setCopied(false), 2000) } catch { setCopied(false) } }
  return <div className="detail-page shell"><div className="detail-top"><Link to="/" className="back-link"><ArrowLeft size={17}/> Все квартиры</Link><div className="detail-top-right"><span>ОБЪЕКТ / {item.id.slice(0,8).toUpperCase()}</span><button className="share-button" onClick={share}>{copied ? <Check size={17}/> : <Share2 size={17}/>} {copied ? 'Ссылка скопирована' : 'Поделиться'}</button></div></div><div className="detail-heading"><div><span className="eyebrow"><span className="eyebrow-line"/> {item.district.name.toUpperCase()} РАЙОН</span><h1>{item.title}</h1><p><MapPin size={17}/>{item.address}</p></div><div className="detail-heading-price"><span>СТОИМОСТЬ</span><b>{price(item.price)}</b><small>{price(Math.round(item.price / item.area))} / м²</small></div></div>
  <div className="gallery"><div className="gallery-main">{images.length ? <img src={images[photo]} alt={`${item.title} — фото ${photo+1}`} /> : <div className="image-placeholder">СРЕДА</div>}{images.length > 1 && <><button className="gallery-arrow previous" aria-label="Предыдущее фото" onClick={() => setPhoto((photo+images.length-1)%images.length)}><ChevronLeft/></button><button className="gallery-arrow next" aria-label="Следующее фото" onClick={() => setPhoto((photo+1)%images.length)}><ChevronRight/></button></>}<div className="gallery-counter">{String(photo+1).padStart(2,'0')} / {String(images.length || 1).padStart(2,'0')}</div></div>{images.length > 1 && <div className="gallery-thumbs">{images.slice(0,3).map((url,i) => <button key={i} className={photo === i ? 'active' : ''} onClick={() => setPhoto(i)} aria-label={`Показать фото ${i+1}`}><img src={url} alt=""/></button>)}</div>}</div>
  <div className="detail-layout"><div className="detail-content"><section className="detail-section"><div className="section-kicker">01 / О КВАРТИРЕ</div><h2>Пространство для жизни</h2><div className="spec-grid"><div><b>{item.rooms === 0 ? 'Студия' : item.rooms}</b><span>{item.rooms === 0 ? 'формат' : 'комнаты'}</span></div><div><b>{area(item.area)}</b><span>общая площадь</span></div><div><b>{item.floor} / {item.total_floors}</b><span>этаж</span></div>{item.kitchen_area && <div><b>{area(item.kitchen_area)}</b><span>кухня</span></div>}</div><p className="description">{item.description || 'Описание не добавлено.'}</p><div className="secondary-specs">{item.building_year && <span>Год постройки <b>{item.building_year}</b></span>}{item.building_type && <span>Тип дома <b>{item.building_type}</b></span>}{item.renovation && <span>Состояние <b>{item.renovation}</b></span>}</div></section>
  <section className="detail-section"><div className="section-kicker">02 / РАЙОН</div><h2>Всё, что вокруг</h2><p className="section-intro">{item.district.description || 'Описание района появится после обработки адреса.'}</p>{item.district.id !== 'pending' ? <><div className="infra-grid"><div><GraduationCap/><b>{f.schools_1km}</b><span>школы в радиусе 1 км</span></div><div><TreePine/><b>{f.parks_1km}</b><span>парка в радиусе 1 км</span></div><div><School/><b>{f.kindergartens_1km}</b><span>детских сада рядом</span></div><div><BusFront/><b>{f.nearest_transport_m} м</b><span>до транспорта</span></div></div><div className="distance-list"><div><span>Ближайшая школа</span><b>{distance(f.nearest_school_m)}</b></div><div><span>Ближайший парк</span><b>{distance(f.nearest_park_m)}</b></div><div><span>Общественный транспорт</span><b>{distance(f.nearest_transport_m)}</b></div></div></> : <div className="info-note">После подключения сервера район и инфраструктура будут рассчитаны по введённому адресу.</div>}{validCoordinates && <a className="map-link" href={`https://www.openstreetmap.org/?mlat=${item.latitude}&mlon=${item.longitude}#map=15/${item.latitude}/${item.longitude}`} target="_blank" rel="noopener noreferrer"><MapPin size={18}/> Посмотреть место на карте <ArrowUpRight size={18}/></a>}</section>
  <section className="detail-section"><div className="section-kicker">03 / ПЕРСПЕКТИВА</div><h2>Что планируется рядом</h2><p className="section-intro">Будущие объекты показаны отдельно от оценки квартиры. Планы и сроки могут меняться — проверяйте первоисточник.</p>{item.development_projects.length ? <div className="projects-list">{item.development_projects.map(p => <div className="project" key={p.id}><div className="project-icon"><BuildingMark type={p.type}/></div><div className="project-copy"><div className="project-meta">{p.type} · {distance(p.distance_m)} · {statusLabel[p.status] || p.status}</div><h3>{p.name}</h3><p>{p.description}</p><small>{p.planned_completion_year ? `Плановый срок: ${p.planned_completion_year} · ` : ''}Источник: {p.source_url ? <a href={p.source_url} target="_blank" rel="noopener noreferrer">{p.source_name} ↗</a> : p.source_name}</small></div></div>)}</div> : <div className="info-note">В доступных данных нет подтверждённых будущих объектов рядом с этой квартирой.</div>}</section></div>
  <aside className="detail-aside"><div className="score-panel"><span className="panel-eyebrow"><Sparkles size={16}/> ОЦЕНКА СООТВЕТСТВИЯ</span>{item.recommendation.score !== null ? <><div className="score-main"><b>{item.recommendation.score}</b><span>/ 100</span></div><div className="score-track"><span style={{ width:`${Math.max(0,Math.min(100,item.recommendation.score))}%` }}/></div><p>Почему этот вариант интересен:</p><ul>{item.recommendation.reasons.map(r => <li key={r}><Check size={16}/>{r}</li>)}</ul></> : <><h3>Оценка готовится</h3><p>Объявление станет доступно рекомендациям после расчёта признаков сервером.</p></>}<div className="score-foot">{item.recommendation.ml_available ? `Модель: ${item.recommendation.model_version}` : 'Без ML · демонстрационный режим'}</div>{item.recommendation.warning && <small className="score-warning">{item.recommendation.warning}</small>}</div><div className="aside-note"><span>ВАШ СЛЕДУЮЩИЙ ШАГ</span><h3>Нашли подходящий вариант?</h3><p>Сохраните ссылку на квартиру и сравните её с другими предложениями.</p><button className="button light" onClick={share}>{copied ? 'Скопировано ✓' : 'Скопировать ссылку'} <ArrowUpRight size={17}/></button></div></aside></div>{isDemo && <div className="demo-disclaimer">Фотографии, цены, адреса, оценки и проекты на этой странице — демонстрационные данные. Это не реальные объявления.</div>}</div>
}
function BuildingMark({type}: {type:string}) { return type === 'Парк' ? <TreePine size={22}/> : type === 'Школа' ? <GraduationCap size={22}/> : <BusFront size={22}/> }
