// Generated by scripts/build-local-media-manifest.mjs.
// Keep this empty in git until the local housing archive is added.
export const localHousingMedia = {} as Record<string, Array<{
  id:string
  url:string
  order:number
  is_cover:boolean
  storage_key?:string
  local_path?:string
  attribution?:string
  rights_status?:string
  publication_allowed?:boolean
}>>
